### ISSUE TITLE
One Vs Rest classifier

### ISSUE THREAD

**Issue by NGBoost** [nkartik94/Multi-Label-Text-Classification#1]
Is it correct to fit an OneVsRestClassifier using''for category in categories:''?
I think that this is not correct in multi label case.
Instead, OneVsRestClassifier should be fitted in the whole train and test set.
Am I correct?

**Comment by nkartik94** [comment]
The basic concept of oneVsRest is to fit it that way, its mentioned in its documentation itself and not fitting on the whole data.
